version: '3.4'

services:
  authservicenodeforgit:
    image: authservicenodeforgit
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
networks:
  TimeOut-network:
    driver: bridge